load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "dsa",
    srcs = [],
    hdrs = ["slist.h"],
    visibility = [
        "//lib:__pkg__",
        "//main:__pkg__",
        "//test:__pkg__",
    ],
)
